
<?=Form::open()?>
    <fieldset>
        <legend>Box</legend>
        <section>
            <div>
                <?=Form::label('Name:', 'boxes.box_name')?>
                <?=Form::input('text', 'boxes.box_name')?>
            </div>
            <div>
                <?=Form::label('Type:', 'boxes.box_type')?>
                <?=Form::select('boxes.box_type', ['html'=>'HTML', 'css'=>'CSS', 'js'=>'JS'])?>
            </div>
        </section>

        <ul class="tabs">
            <li data-active=".tabs li" data-hide=".code_after" data-show=".code_before" class="active">Code before</li>
            <li data-active=".tabs li" data-hide=".code_before" data-show=".code_after">Code after</li>
        </ul>
        <div class="code_before">
            <?=Form::textarea('boxes.code_before')?>
        </div>
        <div class="code_after hide">
            <?=Form::textarea('boxes.code_after')?>
        </div>

        <div>
            <?=Form::submit('Save')?>
        </div>
    </fieldset>
    <?=Form::hidden('boxes.id')?>
<?=Form::close()?>
