
<?=Form::open()?>
    <fieldset>
        <legend>Box</legend>
        <section>
            <label>
                <div>Name:</div>
                <?=Form::input('text', 'boxes.box_name')?>
            </label>
            <label>
                <div>Type:</div>
                <?=Form::select('boxes.box_type', ['html'=>'HTML', 'css'=>'CSS', 'js'=>'JS'])?>
            </label>
        </section>

        <ul class="tabs">
            <li data-active=".tabs li" data-hide=".code_after" data-show=".code_before" class="active">Code before</li>
            <li data-active=".tabs li" data-hide=".code_before" data-show=".code_after">& after boxes</li>
        </ul>
        <div class="code_before">
            <?=Form::textarea('boxes.code_before')?>
        </div>
        <div class="code_after hide">
            <?=Form::textarea('boxes.code_after')?>
        </div>

        <div>
            <?php if (empty($boxes->id)): ?>
                <?=Form::submit('Create', 'name="action" value="create"')?>
            <?php else: ?>
                <a role="button" href="/admin/boxes">New</a>
                <?=Form::submit('Clone', 'name="action" value="clone"')?>
                <?=Form::submit('Update', 'name="action" value="update"')?>
                <?=Form::submit('Delete', 'name="action" value="delete"')?>
            <?php endif; ?>
        </div>
    </fieldset>
    <?=Form::hidden('boxes.id')?>
<?=Form::close()?>
