
<aside>
    <details>
        <summary>Pages</summary>
        <ul>
            <li><a href="/admin/pages">New page</a></li>
        </ul>
    </details>
    <details>
        <summary>Templates</summary>
        <ul>
            <li><a href="/admin/templates">New template</a></li>
        </ul>
    </details>
    <details>
        <summary>Boxes</summary>
        <ul>
            <li><a href="/admin/boxes">New box</a></li>
            <?php View::partial('admin/boxes', '+1', null, "kumbia.boxes"); ?>
        </ul>
    </details>
</aside>
